### ISSUE TITLE
Infinite login redirects?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [fabianbees/docker-openvpn-as#1]
Hi

there was no Issues section to post in your openvpn-as repo, so I had to find another way. :)

After a new install, any time i enter the default admin/passwOrd+2 in the webui, it just keeps taking me to either a page to re-enter them, or this page, but cant go anywhere else:

![image](https://user-images.githubusercontent.com/39491297/196876971-51e05a3e-bcc0-46f4-bd9b-a60a6b856d05.png)

Any idea why?

**Comment by fabianbees** [comment]
> there was no Issues section to post inter your openvpn-as repo, ao I had to find another way. :)

I did not know, that in the open-vpn repo there is no issues section, I will look into this ...



> After a new install, any time i enter the default admin/passwOrd+2 in the webui, it just keeps taking me to either a page to re-enter them, or this page, but cant go anywhere else:
> 
> ![image](https://user-images.githubusercontent.com/39491297/196876971-51e05a3e-bcc0-46f4-bd9b-a60a6b856d05.png)
> 
> Any idea why?


Actually I do have an idea:
Did you go to this URL when wanting to access the admin panel `https://ip-of-host:943/admin/` ?
If you do not include the `/admin/` at the end, you will get to the user-login panel as shown in your screenshot.

I have just tested this behaviour in a clean install, and can confirm that it's working for me as intended.

**Comment by YouveGotMeowxy** [comment]
Hi

Thank you for the help. :)

Yes, I go to the `/admin/` page, then enter the default credentials, it takes me to `/admin/status_overview`, and I click the Agree button, which then takes me to `/?src=connect` with another login page. I re-enter the default credentials, and it takes me to the above screenshot.

From that screen The Profiles Management and Change Password take me to their respective screens, but the Go to Admin panel just takes me back to the login screen. When I re-enter the credentials, I'm back in the loop, starting at the page with the "Agree" button at the bottom.

**Comment by fabianbees** [comment]
I do remember, that I have also experienced this exact issue in the past. Unfortunately, I currently cannot remember what caused it.

As I currently can't reproduce this issue, may I ask you to share your exact Docker run command (or compose file) so I can have a look at it?

You could also try to run the following command and spin up a container where appdata isn't saved outside the container as a test:
```bash
docker run -d \
  --name=openvpn-as-TEST \
  -p 943:943 \
  -p 9443:9443 \
  -p 1194:1194/udp \
  fabianbees/openvpn-as
```
(I do not have any issues, if I do run this exect command.)

**Comment by YouveGotMeowxy** [comment]
Thank you again for trying to help me out, I really do appreciate it.

Unfortunately still no luck, even using that exact docker run you gave me. I literally copy/pasted it, and I get the same result.

If it helps any, the browser console shows this when I first login and it takes me to the "Agree" page:

![image](https://user-images.githubusercontent.com/39491297/197197630-35bd77be-ace6-4468-948d-95799852392e.png)

after I click the Agree button, the console shows this, and I get the screenshot in my original post:

![image](https://user-images.githubusercontent.com/39491297/197197709-9cfc6d73-f7e5-491b-b9e0-7e7247e8d0c8.png)

**Comment by YouveGotMeowxy** [comment]
The exact Compose I'm using is:

```
  openvpn-as:
    hostname: 'openvpn-as'
    image: 'fabianbees/openvpn-as:latest'
    environment:
      TZ: 'America/Chicago'
      PUID: '1000'
      PGID: '1000'
    volumes:
      - '/opt/docker/configs/openvpn/config:/config:rw'
      #- '/mnt/e/Docker/Logs/openvpn/openvpn.log:/config/log/openvpn.log:rw'
    #ports:
      #- '30443:943' # Admin UI
      #- '9443:9443'
      #- '1194:1194/udp'
    networks:
      - 'download'
    deploy:
      mode: 'replicated'
      replicas: 1
      placement:
        constraints:
          - 'node.labels.Main == true'
      resources:
        limits:
          memory: '300M'
      restart_policy:
        condition: 'any'
```

and then I'm also using a reverse proxy (LinuxServer's SWAG/Nginx container), but it doesnt seem like that's causing anything different, since I get the same results whether go direfctly to the IP, or use the reverse proxy):

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name openvpn.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    include /config/nginx/authelia-server.conf;

    location / {
        include /config/nginx/authelia-location.conf;
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app openvpn-as;
        set $upstream_port 943;
        set $upstream_proto https;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location /admin {
        include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app openvpn-as;
        set $upstream_port 943;
        set $upstream_proto https;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```
